### ISSUE TITLE
Dialer crashes

### ISSUE THREAD

**Issue by sultan2304** [shakalaca/android_device_asus_ze520kl#9]
If you want to dial the number during a call, then dialer will crash. I don't know why it doesn't work, but it is

**Comment by jszwedko** [comment]
I've discovered this as well. This appears to be the relevant exception from `adb logcat`:

```
06-26 16:58:52.706  5711  5711 E AndroidRuntime: FATAL EXCEPTION: main                                               
06-26 16:58:52.706  5711  5711 E AndroidRuntime: Process: com.android.phone, PID: 5711       
06-26 16:58:52.706  5711  5711 E AndroidRuntime: java.lang.NoSuchFieldError: No field mDtmfExisted of type Z in class Lcom/qualcomm/qti/internal/telephony/QtiGsmCdmaPhone; or its superclasses (declaration of 'com
.qualcomm.qti.internal.telephony.QtiGsmCdmaPhone' appears in /system/framework/qti-telephony-common.jar)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at com.qualcomm.qti.internal.telephony.QtiGsmCdmaPhone.startDtmf(QtiGsmCdmaPhone.java:261)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at com.android.services.telephony.GsmConnection.onPlayDtmfTone(GsmConnection.java:95)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at android.telecom.ConnectionService.playDtmfTone(ConnectionService.java:891)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at android.telecom.ConnectionService.-wrap16(ConnectionService.java)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at android.telecom.ConnectionService$2.handleMessage(ConnectionService.java:384)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6128)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-26 16:58:52.706  5711  5711 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by shakalaca** [comment]
[qti-telephony-common.ZIP](https://github.com/shakalaca/android_device_asus_Z017/files/1117737/qti-telephony-common.ZIP)

Rename to qti-telephony-common.jar and put under /system/framework.. I de-compile the stock one and didn't find mDtmfExisted field either, so just add it manually.. :)

**Comment by tuanpq1998** [comment]
Thank shakalaca it works

**Comment by jszwedko** [comment]
:+1: worked for me as well
